### ISSUE TITLE
Could't find the specific meaning ofS0,S1,S2,S3,S4....

### ISSUE THREAD

**Issue by zhengkemei** [mlegas/FSM-reinforcement-learning#1]
Hello author, I am glad that you can share your results on github. Your paper is very good, but I encountered some problems in the process of reading:
1.What exactly do S0，S1，S2，S3，S4，S5 in 4.9.1 Pelican crossing refer to?
2.What exactly do S0，S1，S2，S3，S4，S5，S6，S7 in 4.9.2 Toaster device refer to?
Looking forward to your reply.
Thank you！

**Comment by mlegas** [comment]
Hi @zhengkemei,

Thank you for your opinion, I'm glad my work has found some further use.

To answer your questions:
1. The states in my pelican crossing environment refer to the more advanced states of a pelican crossing (https://en.wikipedia.org/wiki/Pelican_crossing) made by Ben Lloyd-Roberts in his thesis:
![obraz](https://user-images.githubusercontent.com/37073845/194117322-6366901b-5f61-4b1a-b3f7-9464453e4ceb.png)

Therefore, S0, S1, S2, S3, S4, and S5 are abstracted states that are shown on the picture above.

Citing directly from his work: 

> _tl_01_ and _tl_02_ represent traffic lights responsible for vehicle signalling. Similarly _pl_01_ and _pl_02_ represent pedestrian lights responsible for controlling foot traffic. Finally, _pb_01_ and _pb_02_ represent physical buttons which issue a pedestrian crossing request when pressed. In order to model the functionality of this pelican crossing we must introduce a set of latches to use in our ladder logic program. To reduce the size of our example program, our pelican crossing model removes the transitional amber aspect from both traffic lights. Therefore each latch {_tl_01, tl_02, pl_01, pl_02_} have two possible states displaying green or red aspects, respectively. Given that both pedestrian buttons issue the same crossing request, we amalgamate inputs from both _pb_01, pb_02_ under the latch _pressed._ Pelican crossings also emit an audio signal to indicate safe crossing conditions for visual impaired pedestrians. Thus we introduce the latch _audio_.

_req_ is a state of whether crossing the street has been requested.

The following image gives a visual representation of what do the latches mean:
![obraz](https://user-images.githubusercontent.com/37073845/194117217-732ebab8-6fdf-442d-bd1a-6410ccfe53cd.png)

Reference: B. Lloyd-Roberts, “Applying reinforcement learning to railway interlocking verification,”
Master’s thesis, Swansea University, Sept 2020.

Unfortunately, I am unable to share his thesis publicly in full. However, you might wish to contact Mr Ben Lloyd-Roberts directly for any further details via e-mail: ben.lloyd-roberts@swansea.ac.uk.

2. Citing from J. Zander, I. Schieferdecker, and P. J. Mosterman, Model-based testing for embedded
systems. CRC Press, 2012:
> The toaster can be started by pushing (_push_) down the latch. As a reaction, the heater is turned on (_on_). The toaster stops toasting (_off_) after a certain time (_time_) or after the stop button (_stop_) has been pressed. Furthermore, the toaster has two heating power levels, one of which can be selected by increasing (_inc_) or decreasing (_dec_) the heating temperature. The toaster also has a defrost function (_defrost_) that results in an additional defrosting time (_time d_) of frozen toast. Note that time is used in our modeling only in a qualitative way, that is, quantitative aspects of timing are not taken into account.
This simple machine consists of two groups of states: _s0 . . . s3_ for regular heating and _s4 . . . s7_ for heating with increased heating power. From the first group of states, the machine accepts an increase of the heating level, which brings it into the appropriate high-power state; vice versa, from this state, it can be brought back by decreasing the heating level. Thus, in this machine only two heating levels are modeled. It is obvious how the model could be extended for three or more such levels. However, with a growing number of levels the diagram would quickly become illegible.

To add to that, _S0_ is a start state when the toaster is not heating anything in the regular heating mode (i.e. we just plugged it to power but have not pressed anything), and _S6_ is a state when the toaster is not heating anything in the increased heating power mode (i.e. we increased the power to the increased heating power mode, but the toaster is not heating anything - it is still in "standby", or rather "off" mode). 

All the best to your research.
